### ISSUE TITLE
Not working with current build of Blender?

### ISSUE THREAD

**Issue by K2mies** [folkertdev/freestyle-gpencil-exporter#3]
Really interested in this tool set and would find it really usefull for current projects. It doesn't seem to run on the current build of Blender, wondering if there is an easy fix?

**Comment by folkertdev** [comment]
Hi, 

The latest commit fixes the issue that I ran into. Please let me know if there's anything else that gives problems. 

the problem: 
The code freezes a color value to use it in a dictionary, and freezing is not possible when a color is owned. Apparently some of the gpencil color values are (now) owned. The fix is to simply clone/copy the color object, and then freeze it.

**Comment by K2mies** [comment]
<img width="1280" alt="screen shot 2018-03-23 at 01 07 11" src="https://user-images.githubusercontent.com/37668497/37803293-9f75649c-2e36-11e8-94fa-378418205abe.png">

Tried updating the .py from the latest commit i could find here. Still seems to have the same issue? If i uncheck the freestyle to grease pencil box the lines will render normally but if i tick it they neither appear in the rendered out put nor as strokes.

**Comment by folkertdev** [comment]
Weird. It could be that the addon didn't update correctly. this behavior is very confusing. 
Did your update process look something like this? 

* download the new version
* open the blender > preferences > addons tab
* turn the freestyle gpencil addon off
* click "install addon from file" and select the new version of the addon 
* turn the addon back on again

If that doesn't work, could you try 

* open a terminal
* run `./blender`
* try to render with the addon enabled
* see whether errors/messages are printed to the shell

If there is anything in there that looks like an error, please post it here.

**Comment by K2mies** [comment]
Hei, thanks for getting back to me on this. Still no luck i'm afriad. Here is the terminal messages. First ran the addon from a clean download, then updated the .py with the commit from here. 

(first run)

> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Applications/Blender/blender.app/Contents/Resources/2.79/scripts/freestyle/modules/parameter_editor.py", line 1575, in process
>     fn(scene, layer, lineset)
>   File "/Users/Hvidsten/Library/Application Support/Blender/2.79/scripts/addons/freestyle_to_gpencil.py", line 359, in lineset_post
>     freestyle_to_strokes(scene, lineset, strokes)
>   File "/Users/Hvidsten/Library/Application Support/Blender/2.79/scripts/addons/freestyle_to_gpencil.py", line 320, in freestyle_to_strokes
>     freestyle_to_gpencil_strokes(strokes, frame, lineset, options)
>   File "/Users/Hvidsten/Library/Application Support/Blender/2.79/scripts/addons/freestyle_to_gpencil.py", line 262, in freestyle_to_gpencil_strokes
>     base_color.freeze()
> TypeError: Cannot freeze wrapped/owned data
> 
> location: <unknown location>:-1
> 
> location: <unknown location>:-1
> 
> Error executing Python script from PythonInterpreter::interpretString
> Name: LineSet
> Errors: 
> Error: Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Applications/Blender/blender.app/Contents/Resources/2.79/scripts/freestyle/modules/parameter_editor.py", line 1575, in process
>     fn(scene, layer, lineset)
>   File "/Users/Hvidsten/Library/Application Support/Blender/2.79/scripts/addons/freestyle_to_gpencil.py", line 359, in lineset_post
>     freestyle_to_strokes(scene, lineset, strokes)
>   File "/Users/Hvidsten/Library/Application Support/Blender/2.79/scripts/addons/freestyle_to_gpencil.py", line 320, in freestyle_to_strokes
>     freestyle_to_gpencil_strokes(strokes, frame, lineset, options)
>   File "/Users/Hvidsten/Library/Application Support/Blender/2.79/scripts/addons/freestyle_to_gpencil.py", line 262, in freestyle_to_gpencil_strokes
>     base_color.freeze()
> TypeError: Cannot freeze wrapped/owned data
> 
> location: <unknown location>:-1



  And then the second time (with updated .py).

> 
> Error: interpretation failed
> reloading addon: freestyle_to_gpencil 1521838415.0 1521838959.0 /Users/Hvidsten/Library/Application Support/Blender/2.79/scripts/addons/freestyle_to_gpencil.py
> Modules Installed () from '/Users/Hvidsten/Downloads/FREESTYLEADDON/freestyle-gpencil-exporter-master/freestyle_to_gpencil.py' into '/Users/Hvidsten/Library/Application Support/Blender/2.79/scripts/addons'
> module changed on disk: /Users/Hvidsten/Library/Application Support/Blender/2.79/scripts/addons/freestyle_to_gpencil.py reloading...
> trying to save userpref at /Users/Hvidsten/Library/Application Support/Blender/2.79/config/userpref.blend ok
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Applications/Blender/blender.app/Contents/Resources/2.79/scripts/freestyle/modules/parameter_editor.py", line 1575, in process
>     fn(scene, layer, lineset)
>   File "/Users/Hvidsten/Library/Application Support/Blender/2.79/scripts/addons/freestyle_to_gpencil.py", line 360, in lineset_post
>     freestyle_to_strokes(scene, lineset, strokes)
>   File "/Users/Hvidsten/Library/Application Support/Blender/2.79/scripts/addons/freestyle_to_gpencil.py", line 321, in freestyle_to_strokes
>     freestyle_to_gpencil_strokes(strokes, frame, lineset, options)
>   File "/Users/Hvidsten/Library/Application Support/Blender/2.79/scripts/addons/freestyle_to_gpencil.py", line 262, in freestyle_to_gpencil_strokes
>     base_color.freeze()
> TypeError: Cannot freeze wrapped/owned data
> 
> location: <unknown location>:-1

**Comment by folkertdev** [comment]
I found the issue, I forgot to merge with the master branch. The same steps you took before will work now.

**Comment by K2mies** [comment]
perfect! That seems to have done the trick (working perfectly now). Thank you for dealing with the issue so promptly and thoroughly! It really is a great tool with interesting applications.

**Comment by folkertdev** [comment]
excellent, good luck!
